### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by zhangy0822** [CuthbertCai/Ask-Confirm#1]
Hi,  I have download DrillDown/data/caches from DrillDown and put the directory under Ask-Confirm/data, but when I run your code, I encountered the following problem: 
![image](https://user-images.githubusercontent.com/57060987/143725828-77d03823-d83b-4aaf-932c-0a3fac82118f.png)
I don't know why this problem occurs, is the data not downloaded correctly or need some pre-processing? I hope you can help me.

**Comment by CuthbertCai** [comment]
Thanks for your comment. It seems that I made a mistake in `scripts/train_image_attribute.sh`, `--n_categories` should be 1601 instead of 501. However, because I'm in Singapore now and cannot access my server in China, maybe I cannot update this repo very quickly. If you meet other issues, please feel free to comment here, I'll try my best to solve them.

**Comment by zhangy0822** [comment]
Thank you for your reply. I will run it first and if there are any questions, I will comment here.

**Comment by zhangy0822** [comment]
When I finished running all Prerequisite and I started running "sh scripts/ train_ppo_coherence. sh", the following problem occurred, probably due to lack of file, I checked the file in date/caches and it did not exist. How is this file generated? Please help me solve this problem when you have time, thanks again.
![image](https://user-images.githubusercontent.com/57060987/143976736-6ae1bf26-ad36-4073-99ba-d47127bfa87c.png)

**Comment by zhangy0822** [comment]
The problem seems to have been resolved and we need to run datasets/word_stats.py to generate the files

**Comment by zhangy0822** [comment]
I have finished the script of training PPO. When I run test_ppo_rules.sh, the following error occurs, and the file may still be missing. If you can find the original documents, I hope you can help me. Another question I would like to ask is how long is the training time of your PPO module? Will it only take a few hours? Or did your script simplify the training process and shorten the training time.
![image](https://user-images.githubusercontent.com/57060987/144691870-3e16f82c-d663-46b9-aa07-0577a4b8366f.png)

**Comment by CuthbertCai** [comment]
Thanks for your comments!
1. For generating `vg_word_stat.npy`, you are right, we need to run `datasets/word_stats.py` first. I update the `README.md` to specify it.
2. For generating `vg_attr_feature`, I add a script, `precomp_vg_attr_feature.sh`, to do it. Also, `README.md` is also updated to describe how to generate it.
3. The training time depends on our settings. If `vg_img_feature`, `vg_img_logits` and `vg_attr_feature` are generated in advance, the training process will be faster than computing them during training. I used a server ( 8 v100 GPUs) to train the model, if `vg_img_feature`, `vg_img_logits` and `vg_attr_feature` are generated in advance, the training time costs several hours (less than 1 day).

**Comment by zhangy0822** [comment]
- Thank you very much for your help, but precomp_vg_attr_feature.py doesn't seem to exist in the datasets folder.
- After generating _vg_img_feature, vg_img_logits_, I run _sh scripts/ train_ppo_coherence. sh_ on my NVIDIA 1080ti. After training 5000epochs (The script says 5000), it only takes about three hours to finish. Is there any wrong setting?

**Comment by CuthbertCai** [comment]
Oh, sorry for the mistake. I update the repo again and push `precomp_vg_attr_feature.py`. According to my log, it took about 23 hours to train 5000 epochs. Because this method doesn't consume GPU memory heavily and the IO speed may affect the training time more obviously, I'm not sure whether your phenomenon is correct or not. Maybe you can test the model and see how the model performs.

**Comment by zhangy0822** [comment]
- Thank you very much for your help, I want to follow your work,  next I will learn your code. I'll let you know if you have any questions.
- There seems to be a slight problem with _precomp_vg_attr_feature.py_, Line 59 _np.save(asp. join(config.data_dir, 'caches/vg_attr_feat. Npy ', attr_feat))_ may need to be changed to _np.save(asp. join(config.data_dir, 'caches/vg_attr_feat. npy '), attr_feat)_ to generate _vg_attr_feat.npy_
