### ISSUE TITLE
device-side assert triggered

### ISSUE THREAD

**Issue by Pefect96** [CuthbertCai/Ask-Confirm#3]
Hi! Thank you very much for your contribution. I have run your code scripts/train_ppo_coherence.sh. But I meet the following bug, maybe the reason is array access out of bounds. Do you know how to solve this bug?
![image](https://user-images.githubusercontent.com/95663989/148709725-6e284f6e-7d68-42ed-9ba2-14dd4b34d8cd.png)

**Comment by CuthbertCai** [comment]
Hi, could you please provide more information about this issue? For example, what is the shape and dtype of `a`, `v` and `log_a`? Because I have never met this issue.

**Comment by Pefect96** [comment]
Hello, I have solved the problem above, maybe there is something wrong with the path of the input file.
